### ISSUE TITLE
What's the best way to append a key parameter to every request URI?

### ISSUE THREAD

**Issue by bdashley** [Indatus/trucker#1]
The remote API does not require user authentication. Instead, it requires a key parameter with the API key to be appended to every request.

Example: 
http://api.somesite.com/item/?key=abcdef

**Comment by benjaminbowles** [comment]
I'm trying to use a custom RestRequest driver, my code for this driver begins as follows:

```
<?php
namespace Trucker\Requests;

class CurrentRestRequest extends RestRequest
{
    public function createRequest(
```

I currently get the following error:

```
InvalidArgumentException
Unsupported driver [current_rest] to load [\Trucker\Requests\CurrentRestRequest]
```
