### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by FrodeMMeling** [Indatus/trucker#20]
Will you add a laravel 5 support soon?

**Comment by bkuhl** [comment]
Upgrading this package's dependencies isn't something we plan to tackle very soon...  If it would help you, we'd welcome a pull request with the updates.

**Comment by andreasba** [comment]
Is there any news about Laravel 5 compatibility?

**Comment by andreasba** [comment]
Any news on your plans for Laravel 5.2 @bkuhl ? :)

**Comment by bkuhl** [comment]
Nothing currently, but we'd welcome pull requests.

**Comment by andreasba** [comment]
Hi @bkuhl there actually is one for L5 already: https://github.com/Indatus/trucker/pull/24 - not sure how much must be changed for 5.2 but 5.1 would be the first step to get there? :)

Thanks
Andreas

**Comment by OskarD** [comment]
@bkuhl I hope you can investigate this sometime soon! I'm sure a lot of people are waiting in anticipation :)

**Comment by bkuhl** [comment]
Thanks for pinging this again @OskarD, I reviewed the MR at https://github.com/Indatus/trucker/pull/24 and have requested a few changes.

**Comment by OskarD** [comment]
@bkuhl awesome!

**Comment by bkuhl** [comment]
Laravel 5 support has been merged in to a `laravel-5` branch (not master).  For inquiries on why this is the case see https://github.com/Indatus/trucker/pull/24#issuecomment-194063905.  If you run into any issues please submit a pull request.

> Note: This project will not be supported for future versions of Laravel. We do not recommend continuing to implement this package in Laravel projects, unless someone else would like to begin to maintain this project (create an issue if you are).
